name: 'CI setup'
description: 'CI setup for clerk-solid'

runs:
  using: 'composite'
  steps:
    - name: Use Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.17

    - name: Install Dependencies
      run: bun install
      shell: bash
