blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/spirit-led-software/clerk-solidjs/discussions
    about: Please ask questions in our discussions forum.
