name: Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI setup
        uses: ./.github/actions/ci-setup
      - name: Run Prettier check
        run: pnpm run format:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI setup
        uses: ./.github/actions/ci-setup
      - name: Run ESLint check
        run: pnpm run lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI setup
        uses: ./.github/actions/ci-setup
      - name: Run TypeScript type check
        run: pnpm run type-check
