name: Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prettier:
    name: 'Prettier'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - name: Run Prettier check
        run: bun run format:check

  eslint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - name: Run ESLint check
        run: bun run lint

  types:
    name: 'TypeScript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - name: Run TypeScript type check
        run: bun run type-check
